### ISSUE TITLE
Create "How to Run" instructions

### ISSUE THREAD

**Issue by camilamaia** [scanapi/demo-api#20]
## Description

Create "How to Run" instructions

**Comment by Pradhvan** [comment]
@camilamaia just to be clear  "How to Run" means instructions on how to run this project locally?

**Comment by Pradhvan** [comment]
I am setting up the project locally. I can create a PR. 😄

**Comment by camilamaia** [comment]
> @camilamaia just to be clear "How to Run" means instructions on how to run this project locally?

Yes, exactly! Sorry for not being completely clear.

**Comment by Pradhvan** [comment]
Not a problem. 😄
