### ISSUE TITLE
Create "How to Deploy" instructions

### ISSUE THREAD

**Issue by camilamaia** [scanapi/demo-api#21]
## Description

Create "How to Deploy" instructions

**Comment by Pradhvan** [comment]
@camilamaia would there be much difference in deploying documentation for different cloud providers? I have a personal server hosted on Digital Ocean, I can document the process and create a PR for the same. How does that sound?

**Comment by camilamaia** [comment]
@Pradhvan the code is hosted in Heroku, and I have enabled the automatic deploy for the project. So, every time the code is merged into the `main` branch, a deploy happens. We can see the deploys log here: https://github.com/scanapi/demo-api/deployments

For this ticket, basic we just have to add this info to the readme file:
- every time the code is merged into the `main` branch, a deploy happens
- deploys log link: https://github.com/scanapi/demo-api/deployments

Thanks for the help documenting stuff here 🙇‍♀️🙇‍♀️🙇‍♀️

**Comment by Pradhvan** [comment]
Great! This looks more simple than I had eventually imagined. Will create a PR by tomorrow evening IST. 😄
