### ISSUE TITLE
Migrate from Heroku

### ISSUE THREAD

**Issue by camilamaia** [scanapi/demo-api#60]
After November 28, 2022, we will need to start paying for using Heroku Postgres. To avoid that, let's migrate to another service.

> Starting November 28, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® plans will no longer be available. We will begin to scale down existing dynos and delete databases with free plans on this date. You also can’t provision new dynos or databases on free plans.

> You must [upgrade your dynos and databases](https://help.heroku.com/81MBEG7L/how-do-i-upgrade-from-heroku-s-free-tier-and-begin-using-paid-resources) to avoid disruption to your apps or the deletion of data. See [the announcement on our blog](https://blog.heroku.com/next-chapter) and our [FAQs](https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq) for more details.

https://devcenter.heroku.com/changelog-items/2461
https://blog.heroku.com/next-chapter

**Comment by Pradhvan** [comment]
We can try moving the API to [fly.io](https://fly.io/) I have seen some good articles too around it too. 

https://learndjango.com/tutorials/deploy-django-postgresql-flyio

https://testdriven.io/blog/django-fly/

Do we have an account/email that we use for heroku ?

**Comment by camilamaia** [comment]
(btw, @Pradhvan this is the list of services that you should have access to, let me know if anything else is missing
https://github.com/scanapi/contributors/blob/main/CORE_TEAM.md#core-team-members-accesses)

**Comment by Pradhvan** [comment]
> Nice, I like the idea, I was also thinking about fly.io. Yes, I have just added you to the app, let me know if you received the invite. I thought you were already there, but I guess I missed this one when I was sending you all the invites for being a core developer 😅 sorry!

No problem. I am testing out fly.io, have created organisation in it and invited you. Will update you as admin once you join the organisation.

**Comment by camilamaia** [comment]
It is live again http://demo.scanapi.dev/ 🎉 

Unfortunately, I don't know where I stored the backup file 😞 So we will have to start with an empty database again.
